---
title: "Betting Methods"
author: "Will Renius"
date: "November 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
#detach("package:stats")
library(tidyverse)
library(lubridate)
```


```{r}
load("data/aggregated_mens.RData")
men.data <- t2
```

```{r}
str(men.data)
```


```{r}
win.odds.columns <- c("B365W", "B.WW" , "CBW" , "EXW" , "LBW" , "GBW" , "IWW" , "PSW" , "SBW" , "SJW" , "UBW" )
lose.odds.columns <- c("B365L", "B.WL" , "CBL" , "EXL" , "LBL" , "GBL" , "IWL" , "PSL" , "SBL" , "SJL" , "UBL" ) 
win.odds.col.nums <- match(win.odds.columns,names(men.data))
lose.odds.col.nums <- match(lose.odds.columns,names(men.data))

men.data %>% select(win.odds.col.nums) %>% apply(1, function(x) sum(!is.na(x))) -> men.data$countWinOdds

men.data %>% select(lose.odds.col.nums) %>% apply(1, function(x) sum(!is.na(x))) -> men.data$countLoseOdds

#already done double checked, avgL same values
#men.data %>% select(lose.odds.col.nums) %>% apply(1, function(x) mean(x, na.rm = T) )-> men.data$meanLoseOdds

#men.data %>% select(win.odds.columns) %>% apply(1, function(x) mean(x, na.rm = T) )-> men.data$meanWinOdds
```
```{r}
#men.data %>% filter (meanLoseOdds != avgW)
```



```{r}
ggplot(data = men.data, mapping = aes(avgW)) + geom_histogram(binwidth = 0.01)
ggplot(data = men.data, mapping = aes(avgL)) + geom_histogram(binwidth = 0.01)

```
```{r}
men.data %>% separate(Date, c("day", "month", "year"), "/") %>% dplyr::filter(countWinOdds > 4, year > "13") %>% ggplot(., mapping = aes(avgW, avgL)) + geom_point() + coord_trans(y = "log10", x ="log10")

```
```{r}
men.data %>% separate(Date, c("month", "day", "year"), "/") %>% dplyr::filter(countWinOdds > 4, year < "12") %>% ggplot(., mapping = aes(avgW, avgL)) + geom_point() + coord_trans(y = "log10", x ="log10")
```
```{r}
men.data %>% separate(Date, c("day", "month", "year"), "/") %>% dplyr::filter(countWinOdds > 4, year == "13") %>% ggplot(., mapping = aes(avgW, avgL)) + geom_point() + coord_trans(y = "log10", x ="log10")
```
Somthing weird happened in 2013, might be interesting to explore more
```{r}
dates <- mdy(men.data$Date)
#print(dates)
men.data$date.new <- dates
str(men.data)
```

```{r}
men.data %>% filter(avgW > avgL + 10) %>% summarize(count = n())
men.data %>% filter(avgW < avgL - 10) %>% summarize(count = n())
```

```{r}
#men.data %>% group_by(ATP, Tournament ) %>% summarize(count = n()) %>% arrange(desc(count))
#str(men.data)
#remove all the 
dates <- mdy(men.data$Date)
men.data$date.new <- dates
data.filtered <- men.data  %>% select(-W1, -L1, -W2, -L2, -W3, -L3, -W4, -L4, -W5, -L5, -Wsets, -Lsets, -Comment)
data.filtered <- select(data.filtered, -Date, -Winner, -Loser, - Tournament, -Location)
data.filtered$LRank <- as.integer(data.filtered$LRank)
data.filtered$LPts <- as.integer(data.filtered$LPts)
data.filtered <- mutate(data.filtered, upset = as.factor(WRank > LRank))
train.data <- data.filtered %>% dplyr::filter(date.new < as.Date("2017-01-01")) %>% select(-date.new)
test.data <- data.filtered %>% dplyr::filter(date.new > as.Date("2004-01-01"), date.new < as.Date("2018-01-01")) %>% select(-date.new)

#train.data.filtered <- train.data %>% dplyr::filter(countWinOdds == 5, countLoseOdds == 5) %>% select(-Round, -Best.of, -Series)

train.data.filtered <- sample_n(train.data, 100)
test.data.filtered <- sample_n(test.data, 100)

str(train.data.filtered)
str(test.data.filtered)
#str(train.data.filtered)
#str(data.filtered)

```
```{r}
save(data.filtered, file = "filtered.men.data.RData")

```

```{r}
test.data %>% group_by(upset) %>% summarize(count = n())
```

```{r}
require(randomForest)
test.imputed <-  rfImpute(upset ~ .,test.data.filtered)
train.imputed <- rfImpute(upset ~ .,train.data.filtered)

Boston.rf=randomForest( x = select(train.imputed, -upset) , y = train.imputed$upset, xtest = select(test.imputed,-upset), ytest = test.imputed$upset)
plot(Boston.rf)

```
```{r}
#rfImpute
```

```{r}
# Convert character vector to list of symbols
dots <- lapply(win.odds.columns, as.symbol)
#test.filtered <- data.filtered
win.odds.col.nums.2 <- match(win.odds.columns,names(data.filtered))
print(win.odds.columns)
print(win.odds.col.nums.2)
#test.filtered <- mutate_each(data.filtered, funs(ifelse(is.na(.), 0, 1)))

for(col.index in win.odds.col.nums.2){
  print(col.index)
  print(sum(!is.na(data.filtered[,col.index])))
}

#test.filtered %>% group_by(.dots=dots) %>% summarise(count = n()) %>% arrange(desc(count))
```




```{r}
save(men.data, file = "men.data.RData")

```


