---
title: "Project"
author: "Nick Kurtansky"
date: "11/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(plyr)
```

### Import data
```{r}
d.01 <- read.csv("2001.csv", header = TRUE)
d.02 <- read.csv("2002.csv", header = TRUE)
d.03 <- read.csv("2003.csv", header = TRUE)
d.04 <- read.csv("2004.csv", header = TRUE)
d.05 <- read.csv("2005.csv", header = TRUE)
d.06 <- read.csv("2006.csv", header = TRUE)
d.07 <- read.csv("2007.csv", header = TRUE)
d.08 <- read.csv("2008.csv", header = TRUE)
d.09 <- read.csv("2009.csv", header = TRUE)
d.10 <- read.csv("2010.csv", header = TRUE)
d.11 <- read.csv("2011.csv", header = TRUE)
d.12 <- read.csv("2012.csv", header = TRUE)
d.13 <- read.csv("2013.csv", header = TRUE)
d.14 <- read.csv("2014.csv", header = TRUE)
d.15 <- read.csv("2015.csv", header = TRUE)
d.16 <- read.csv("2016.csv", header = TRUE)
d.17 <- read.csv("2017.csv", header = TRUE)

total <- rbind.fill(d.01, d.02, d.03, d.04, d.05, d.06, d.07, d.08, d.09, d.10, d.11, d.12, d.13, d.14, d.15, d.16, d.17)
```

```{r}
total %>% arrange(Date)
```


```{r}
t2 <- total %>% select(-c(length(total), length(total) - 1, length(total) - 2, length(total) - 3))
```

```{r}
length(t2)
#summary(t2)
```

```{r}
avgW <- rep(NA,nrow(t2))
avgL <- rep(NA,nrow(t2))
t2$avgW <- avgW
t2$avgL <- avgL
for(i in 1:nrow(total.2)){
  t2$avgW[i] <- mean(c(t2$CBW[i], t2$GBW[i], t2$IWW[i], t2$SBW[i], t2$B365W[i], t2$B.WW[i], t2$EXW[i], t2$PSW[i], t2$UBW[i], t2$LBW[i], t2$SJW[i]), na.rm = TRUE)
  t2$avgL[i] <- mean(c(t2$CBL[i], t2$GBL[i], t2$IWL[i], t2$SBL[i], t2$B365L[i], t2$B.WL[i], t2$EXL[i], t2$PSL[i], t2$UBL[i], t2$LBL[i], t2$SJL[i]), na.rm = TRUE)
}
```


```{r}
t2
```


```{r}
save(t2, file = "aggregated_mens.RData")
```

