
---
title: "Random Forest"
author: "Will Renius"
date: "November 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
#install.packages("fastAdaboost")
#install.packages("randomForest")
#install.packages("e1071")
#detach("package:stats")
library(tidyverse)
library(lubridate)
library(fastAdaboost)
library(e1071)
library(randomForest)
library(scales)
```


```{r}
load("data/favorite.data.RData")
men.data <- favorite.data
```

```{r}
str(men.data)
```


```{r}
#men.data %>% group_by(rank.upset) %>% summarize(count = n())

```


```{r}
train.data <- men.data %>% dplyr::filter(date.new < as.Date("2017-01-01")) %>% select(-date.new)
test.data <- men.data %>% dplyr::filter(date.new > as.Date("2017-01-01")) %>% select(-date.new)
#, date.new < as.Date("2018-01-01")
```





```{r}
require(randomForest)
imputed.data <- men.data
imputed.data$favorite_won <- as.factor(!imputed.data$odds.upset)
character.columns <- c("Location", "Tournament", "Series", "Surface", "Court","Round" )
for(col.name in character.columns){
  imputed.data[[col.name]]<- as.factor(imputed.data[[col.name]])
}

favorite.columns <- c("B365F", "B.WF" , "CBF" , "EXF" , "LBF" , "GBF" , "IWF" , "PSF" , "SBF" , "SJF" , "UBF" )
underdog.columns <- c("B365U", "B.WU" , "CBU" , "EXU" , "LBU" , "GBU" , "IWU" , "PSU" , "SBU" , "SJU" , "UBU")

for(col.name in favorite.columns){
  imputed.data[[col.name]][is.na(imputed.data[[col.name]])] <- imputed.data[["avgF"]][is.na(imputed.data[[col.name]])]
}
for(col.name in underdog.columns){
  imputed.data[[col.name]][is.na(imputed.data[[col.name]])] <- imputed.data[["avgU"]][is.na(imputed.data[[col.name]])]
}

imputed.data <- imputed.data %>% na.omit() %>% select(-maxWinOdds, -minLoseOdds, -maxProfit, -rank.upset, -year, -odds.upset, -Tournament, -Location)
str(imputed.data)

```
```{r}
# theme
my.theme <- theme(axis.text.x=element_text(face="bold",color="cyan4", size=10), axis.text.y=element_text(face="bold",color="cyan4",size=10), axis.title = element_text(face="bold",color="royalblue4",size=13), plot.title = element_text(face="bold",color="violetred4",size=15,hjust=.5), legend.title=element_blank(), plot.subtitle = element_text(face="bold", color="royalblue4", size=10, hjust=.5))

```


```{r}
plot.winnings <- function(df, title){
  df.new.pred <- df %>% dplyr::filter(is.finite(winnings)) %>% arrange(date.new) %>% mutate(winnings = cumsum(winnings))
      # print(all.new.pred)
  plot.df <- ggplot(df.new.pred, aes(date.new, winnings)) + geom_line(color='orange3', size=1) + xlab("Date") + ylab("Winnings") + ggtitle(title)
  
  print(plot.df)
}
```

loop through everything
```{r}
rf.final.payouts = c()
svm.final.payouts =c()
reg.final.payouts = c()
boost.final.payouts = c()
for(i in 2011:2017){
  train.start.date <-  paste0(i-3, "-01-01", sep = '')
  train.end.date <- paste0(i-1, "-01-01", sep = '')
  test.start.date <- paste0(i, "-01-01", sep = '')
  test.end.date <- paste0(i+1, "-01-01", sep = '')
  print(test.start.date)
  
  new.train <- imputed.data %>% dplyr::filter(date.new < as.Date(train.end.date), date.new >= as.Date(train.start.date)) 
  
  test.data <- imputed.data %>% dplyr::filter(date.new > as.Date(test.start.date), date.new < as.Date(test.end.date))
  print(str(test.data))
  
  #Make predictive models

  # rf.model = randomForest(favorite_won~., data=new.train, ntree=20, proximity=T)
  # rf.prediction = predict(rf.model, newdata=test.data)
  # rf.pred <- test.data
  # rf.pred$prediction <- rf.prediction
  # rf.bets <- rf.pred %>% mutate( winnings = case_when(prediction != favorite_won ~-bet,
  #                                            prediction == "TRUE" & favorite_won == prediction  ~ bet * (FMaxOdds -1),
  #                                            prediction == "FALSE" & favorite_won == prediction ~ bet * (UMaxOdds -1),
  #                                            TRUE ~ NA_real_))
  # plot.winnings(rf.bets, paste(test.start.date, "Random Forest Winnings"))
  # rf.final.payouts <-  c(rf.final.payouts, sum(rf.bets$winnings))
  # #importance of each column
  # print(importance(rf.model))
  # print(rf.model)
  #SVM
  # kernels = c("linear", "polynomial", "radial", "sigmoid")
  # for(k in kernels){
  #   svm.model <- svm(favorite_won~., data = new.train, kernel = k)
  #   svm.prediction <- predict(svm.model, test.data)
  #   svm.pred <- test.data
  #   svm.pred$prediction <- svm.prediction
  #   svm.bets <- svm.pred %>% mutate( winnings = case_when(prediction != favorite_won ~-bet,
  #                                              prediction == "TRUE" & favorite_won == prediction  ~ bet * (FMaxOdds -1),
  #                                              prediction == "FALSE" & favorite_won == prediction ~ bet * (UMaxOdds -1),
  #                                              TRUE ~ NA_real_))
  #   plot.winnings(svm.bets, paste(test.start.date, k, "Support Vector Machine Winnings"))
  #   svm.final.payouts <-  c(svm.final.payouts, sum(svm.bets$winnings))
  # }
  
  # 
  #Log Reg
  reg.model <- glm(favorite_won ~.,family=binomial(link='logit'),data=new.train)
  reg.prediction <- as.factor(predict(reg.model, test.data, type = "response") < .5)
  reg.pred <- test.data
  reg.pred$prediction <- reg.prediction
  reg.bets <- reg.pred %>% mutate( winnings = case_when(prediction != favorite_won ~-bet,
                                             prediction == "TRUE" & favorite_won == prediction  ~ bet * (FMaxOdds -1),
                                             prediction == "FALSE" & favorite_won == prediction ~ bet * (UMaxOdds -1),
                                             TRUE ~ NA_real_))
  print(summary(reg.model))
  print(table(reg.pred$favorite_won, reg.prediction > 0.5))
  print(table(reg.pred$favorite_won, reg.prediction < 0.5))


  # reg.final.payouts <-  c(reg.final.payouts, sum(reg.bets$winnings))
  plot.winnings(reg.bets, paste(test.start.date, "Logistic Regression Winnings"))
  # #Addaboost
  # boost.model <- adaboost(favorite_won ~., new.train, nIter = 20)
  # boost.prediction <- predict( boost.model,test.data)$class
  # boost.pred <- test.data
  # boost.pred$prediction <- boost.prediction
  # boost.bets <- boost.pred %>% mutate( winnings = case_when(prediction != favorite_won ~-bet,
  #                                            prediction == "TRUE" & favorite_won == prediction  ~ bet * (FMaxOdds -1),
  #                                            prediction == "FALSE" & favorite_won == prediction ~ bet * (UMaxOdds -1),
  #                                            TRUE ~ NA_real_))
  # plot.winnings(boost.bets, paste(test.start.date, "AdaBoost Winnings"))
  # boost.final.payouts <-  c(boost.final.payouts, sum(boost.bets$winnings))
  # #append final payouts
  # 
  
  
  
}
# final.payouts <- data.frame(random.forest = rf.final.payouts, svm = svm.final.payouts, log.reg = reg.final.payouts, ada.boost = boost.final.payouts)
# final.payouts
```

```{r}
boost.model <- adaboost(favorite_won ~., new.train, nIter = 20)
get_tree(boost.model, 1)
```
```{r}
svm.model$SV
```


